# Eureka Server runs on port 8761 (Standard port for Eureka)
server.port=8761
spring.application.name=eureka-server

# Tell this server NOT to register itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false